---

- name: simple-provisioning
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: ap-northeast-2
    vpc_name: simple-vpc
    vpc_cidr_block: 10.210.0.0/16
    subnet_cidr_block: 10.210.1.0/24
    instance_image: ami-0b827f3319f7447c6
    ec2_key_name: btc-key
    instance_type: t3.nano
    
  tasks:
  - name: create vpc
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ aws_region }}"
      tags:
        Name: "{{vpc_name}}"
      tenancy: default
    register: result_vpc
    
  - name: Create subnet for database servers
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ result_vpc }}"
      cidr: "{{ subnet_cidr_block }}"
      region: "{{ aws_region }}"
      tags:
        Name: webserver_Subnet
    register: result_subnet